title:        RRT
tagline:      'Reproducibile R Toolkit'
description:  'Reproducibile R Toolkit'
url:          https://github.com/RevolutionAnalytics/RRT
permalink:    /:year/:month/:title/
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
markdown:     rdiscount
pygments:     true
paginate:     3
version:      0.1
